swagger: '2.0'
info: 
  title: 'Cinema Service'
  version: '0.1'
host: 'localhost:7777'
schemes:
  - http
produces:
  - application/json
paths:
  /cinemas:
    get:
      summary: Retrieves all existing cinemas
      operationId: cinemas
      produces: [ application/json ]
      responses:
        200:
          description: Contains details of all cinemas
          schema:
            type: array
            items: 
              $ref: '#/definitions/Cinema'
        400:
          description: 'Invalid request'
    post:
      summary: Creates a new cinema
      operationId: addCinema
      consumes: [ application/json ]
      parameters:
      - in: body
        name: cinema
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
              example: Bad cinema
            description:
              type: string
              example: A pretty terrible cinema
            capacity:
              type: integer
              example: 100
      responses:
        201:
          description: Creates the cinema
        400:
          description: 'Invalid request'
  /cinemas/{id}:
    get:
      summary: Retrieves a single existing cinema
      produces: [ application/json ]
      parameters:
      - name: id
        in: path
        description: ID of the cinema.
        required: true
        type: string
      responses:
        200:
          description: Retrieves the cinema
        400:
          description: Invalid request
    delete:
      summary: Deletes a single existing cinema
      produces: [ application/json ]
      parameters:
      - name: id
        in: path
        description: ID of the cinema.
        required: true
        type: string
      responses:
        200:
          description: Deletes the cinema
        400:
          description: Invalid request
    put:
      summary: Updates a single existing cinema
      produces: [ application/json ]
      parameters:
      - name: id
        in: path
        description: ID of the cinema.
        required: true
        type: string
      - in: body
        name: cinema
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
              example: Updated cinema
            description:
              type: string
              example: A pretty updated cinema
            capacity:
              type: integer
              example: 34
      responses:
        200:
          description: Updates the cinema
        400:
          description: Invalid request

              
definitions:
  Cinema:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      capacity:
        type: number
    required:
      - name
      - description
      - capacity