swagger: '2.0'
info: 
  title: 'Cinema Service'
  version: '0.1'
host: 'localhost:7777'
schemes:
  - http
produces:
  - application/json
paths:
  /cinemas:
    get:
      summary: Retrieves all existing cinemas
      operationId: cinemas
      produces: [ application/json ]
      responses:
        200:
          description: Contains details of all cinemas
          schema:
            type: array
            items: 
              $ref: '#/definitions/Cinema'
        400:
          description: 'Invalid request'
    post:
      summary: Creates a new cinema
      operationId: addCinema
      consumes: [ application/json ]
      parameters:
        - name: name
          in: body
          description: Name of the cinema
          schema:
            type: string
          example: "Bad cinema"
        - name: description
          in: body
          description: Description of the cinema
          schema:
            type: string
          example: "A pretty terrible cinema"
        - name: capacity
          in: body
          description: Capacity of the cinema
          schema:
            type: number
          example: 100
      responses:
        201:
          description: Creates the cinema
        400:
          description: 'Invalid request'
              
definitions:
  Cinema:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      capacity:
        type: number
    required:
      - name
      - description
      - capacity